<?php

namespace AppBundle\Repository;

/**
 * TipoTorneoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoTorneoRepository extends \Doctrine\ORM\EntityRepository
{
}
