<?php

namespace AppBundle\Repository;

/**
 * TorneosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TorneosRepository extends \Doctrine\ORM\EntityRepository
{
}
