app:
    resource: '@AppBundle/Controller/'
    type: annotation

inicio:
    path:     /
    defaults: { _controller: AppBundle:Default:index }


user_registration:
    path:     /register
    defaults: { _controller: AppBundle:User:register }
