app:
    resource: '@AppBundle/Controller/'
    type: annotation



index:
    path:     /
    defaults: { _controller: AppBundle:Index:index }

login_check:
    path: /login_check
    defaults: { _controller: AppBundle:Index:loginCheck }

logout:
    path: /logout

administrator:
    path: /admin
    defaults: {_controller: AppBundle:Admin:principal }

gestion_usuarios:
    path: /admin/usuarios
    defaults: {_controller: AppBundle:Admin:userManagement }

user_delete:
    path: /admin/usuarios/delete/{id}
    defaults: {_controller: AppBundle:Admin:delete}
    methods: [POST, DELETE]

user_block:
    path: /admin/usuarios/bloquear/{id}
    defaults: {_controller: AppBundle:Admin:block}
    methods: [POST, PUT]

user_unblock:
    path: /admin/usuarios/desbloquear/{id}
    defaults: {_controller: AppBundle:Admin:unblock}
    methods: [POST, PUT]

gestion_torneos:
    path: /admin/torneos
    defaults: {_controller: AppBundle:Admin:torneosManagement }

homepage:
    path:     /home
    defaults: { _controller: AppBundle:User:home }

carnet:
    path: /carnet
    defaults: {_controller: AppBundle:User:carnet }

torneo_section:
    path: /torneo/{section}
    defaults: {_controller: AppBundle:User:torneoSection}
