app:
    resource: '@AppBundle/Controller/'
    type: annotation

homepage:
    path:     /home
    defaults: { _controller: AppBundle:User:home }

user_registration:
    path:     /register
    defaults: { _controller: AppBundle:User:register }

index:
    path:     /
    defaults: { _controller: AppBundle:User:index }

login_check:
    path: /login_check
    defaults: { _controller: AppBundle:User:loginCheck }

logout:
    path: /logout
