app:
    resource: '@AppBundle/Controller/'
    type: annotation

homepage:
    path:     /home
    defaults: { _controller: AppBundle:User:home }

index:
    path:     /
    defaults: { _controller: AppBundle:Index:index }

login_check:
    path: /login_check
    defaults: { _controller: AppBundle:Index:loginCheck }

logout:
    path: /logout

administrator:
    path: /admin
    defaults: {_controller: AppBundle:Admin:principal }

gestion_usuarios:
    path: /admin/usuarios
    defaults: {_controller: AppBundle:Admin:userManagement }

carnet:
    path: /carnet
    defaults: {_controller: AppBundle:User:carnet }

torneo_section:
    path: /torneo/{section}
    defaults: {_controller: AppBundle:User:torneoSection}
